- CreateDevelopmentProfile/handler.ts
- openapi/index.yaml
- package.json
- utils/conversions.ts
- yarn.lock
This PR aims to use the extended service model that includes also the services metadata.
> [#170127598] Use the extended service model that includes metadata

- azure-pipelines.yml
- package.json
- yarn.lock
This is an Azure DevOps pipeline to build, check source codes, run tests, and more.
This pipeline has been implemented to be run on hosted agent pools based both on 'windows-2019' and 'ubuntu-latest' virtual machine images and using the scripts defined in the package.json file.
> [#171182749] Created Azure DevOps pipeline

- GetServices/__tests__/handler.test.ts
- GetServices/function.json
- GetServices/handler.ts
- GetServices/index.ts
- openapi/index.yaml
- package.json
- yarn.lock
This PR aims to add a function to get the collection of all services.
> [#170129433] Get all services

- .artifactignore
- azure-pipelines.yml
- package.json
- yarn.lock
Some notes about the changes:
- file `azure-pipelines.yaml`: 
-- added two new 'pipeline stages' (`Deploy_production` and `Deploy_staging`) to the Azure DevOps pipeline to manage the deployment of the Function app (see attached screenshot);   
-- all the deployment jobs are disabled by default, to enable them the following variable need to be defined and configured in the Azure pipeline (e.g. using web portal): `DO_DEPLOY: True`
-- two alternative deployment methods are supported: using slots or without slots (you can select the preferred method setting the variable `DEPLOY_TO_SLOT`)  
-- if enabled and all checks are passed (build, lint, lint_api, unit_test, etc.) the deployment in the staging environment is performed when there is a push on 'master' branch; the deployment in production …
> [#171324301] Added CD to azure devops pipeline

- .artifactignore
- azure-pipelines.yml
- azure-templates/deploy-steps.yml
- azure-templates/make-build-steps.yml
The following changes have been implemented to improve the current Azure DevOps pipeline for this repository:
- moved all the build packaging tasks from _Build_ stage (always executed) to _Deploy_x_ stages to **accelerate** the pipeline execution when deployment is skipped (i.e. not required)
- added **templates** usage to allow the reuse of several recurrent steps in the pipeline (e.g. install node modules and build, deploy a function, etc.): this improve readability, maintenance and reuse of content, logic, and parameters
- reviewed the conditions and renamed the pipeline **variables** to support the manual execution of specific jobs on-demand (e.g. allow administrators to execute the deployment of a specified branch or commit in production regardless ‘latest’ tag)
- modified the …
> [#171536663] Several pipeline improvements

- README.md
- UpdateVisibleServicesCache/function.json
- UpdateVisibleServicesCache/index.ts
- UpdateVisibleServicesCacheActivity/function.json
- UpdateVisibleServicesCacheActivity/index.ts
- UpdateVisibleServicesCacheOrchestrator/function.json
- UpdateVisibleServicesCacheOrchestrator/index.ts
- UploadServiceLogo/function.json
- env.example
- package.json
- utils/conversions.ts
- yarn.lock
Adds a scheduled function to save to a public blob storage behind a CDN:
- visible-services.json 
- visible-services-by-scope.json 
- <serviceId>.json (for each visible service, contains service metadata)
> add scheduled function to update service cache

- GetUser/handler.ts
- UpdateUserGroups/__tests__/handler.ts
- UpdateUserGroups/function.json
- UpdateUserGroups/handler.ts
- UpdateUserGroups/index.ts
- openapi/index.yaml
- utils/apim.ts
This PR aims to add a function to edit the list of groups associated with a specific user from the API management.
> [#171549167] Add function to update the group list of a specific user

- CreateUser/__tests__/handler.ts
- CreateUser/function.json
- CreateUser/handler.ts
- CreateUser/index.ts
- README.md
- env.example
- openapi/index.yaml
- package.json
- yarn.lock
This PR aims to create a User on the Active Directory Azure B2C and on the API Management.
> [#171549246] Add function to create a new user

- openapi/index.yaml
This PR aims to fix the definition of the uploadServiceLogo operation in specs file in order to allow the generation of its correct request type by `io-utils`
> [#171784612] Fix parameters definition for uploadServiceLogo operation

- UpdateVisibleServicesCache/function.json
- UpdateVisibleServicesCacheActivity/function.json
- UploadServiceLogo/function.json
reverts #33 due to a bug in the azure function runtime:
https://github.com/Azure/azure-functions-host/issues/3804
> [#171890294] revert blob web path

- GetServices/handler.ts
This PR includes a fix to GetServices that now returns all services, instead of a subset.
> [#174644239] - Fix GetServices returns all services

- openapi/index.yaml
This PR adds a FiscalCode ref in swagger definitions
> [#174727490] add FiscalCode ref

- DeleteUserDataActivity/__tests__/backupAndDelete.test.ts
- __mocks__/mocks.ts
This PR is supposed to fix an unwanted behaviour which makes the user data delete process to stop when no content is found on blob storage for a given message. 
I've added some tests over the process and played with different scenarios, but I could not reproduce the issue yet. Still tests are valuable to keep.
> [#174597188] Continue delete if message content is not found

- openapi/index.yaml
- utils/conversions.ts
This PR:
- modifies the `Subscription`' s property `id` mapping.
- modifies `Subscription`' s definition in order to remove unnecessary properties
> [#174844930] Restrict subscription(s) output payload properties

- ExtractUserDataActivity/__tests__/handler.test.ts
- ExtractUserDataActivity/handler.ts
This PR solves a bug for which, when a user request his/her data to be downloaded, if he/she has at leas one message with no related notification (this case is legal) the request fails.
> [#174850132] Prevent errors on missing notification

- CreateUser/handler.ts
- GetUser/__tests__/handler.test.ts
- GetUser/handler.ts
- GetUser/index.ts
- openapi/index.yaml
- utils/apim.ts
This PR is useful to retrieve custom extension property `token_name` from Azure AD B2C, while calling `GetUser` API. Property value is also mapped into `UserInfo` API model in order to make possible info's propagation to io-functions-services.
> [#174823724] Add token name to GetUser from Azure ADB2C

- CreateDevelopmentProfile/index.ts
- CreateService/index.ts
- CreateSubscription/index.ts
- CreateUser/index.ts
- DeleteUserDataActivity/index.ts
- ExtractUserDataActivity/index.ts
- GetProfileActivity/index.ts
- GetService/index.ts
- GetServices/index.ts
- GetSubscriptionKeys/index.ts
- GetUser/index.ts
- GetUserDataProcessingActivity/index.ts
- GetUsers/index.ts
- RegenerateSubscriptionKeys/index.ts
- SendUserDataDeleteEmailActivity/index.ts
- SendUserDataDownloadMessageActivity/index.ts
- SetUserDataProcessingStatusActivity/index.ts
- SetUserSessionLockActivity/index.ts
- UpdateService/index.ts
- UpdateSubscriptionsFeedActivity/index.ts
- UpdateUserGroups/index.ts
- UpdateVisibleServicesActivity/index.ts
- UploadServiceLogo/index.ts
- UserDataDeleteOrchestrator/index.ts
- UserDataDownloadOrchestrator/cli.ts
- utils/__tests__/config.test.ts
- utils/config.ts
- utils/cosmosdb.ts
- utils/email.ts
This PR introduces the `utils/config` module which aims to be the unique interface for application configuration. 
Every place in which the application used to directly access env variable has been refactored to use this module instead.
> [#175059122] Centralise config read

- openapi/index.yaml
This PR adds missing unauthorized response to operations that could return 401, with focus on `GetUser` and `CreateSubscription`
> [#175170499] Add missing unauthorized to openapi specs

- CreateUser/__tests__/handler.ts
- CreateUser/handler.ts
- UpdateUser/__tests__/handler.ts
- UpdateUser/function.json
- UpdateUser/handler.ts
- UpdateUser/index.ts
- openapi/index.yaml
This PR is intended to manage ADB2C custom attribute `Token Name`, in order to allow existing `CreateUser` and the brand new `UpdateUser` to manage this custom attribute.
> [#175227073] Allow updating ADB2C User and introduce Token Name management on Create/Update operations

- utils/random.ts
This change is needed because windows systems fails to unzip an authenticated archive when password has certain characters. 
The solution is to use only a subset of 7bit ASCII characters which are also easy to read by humans.
> [#175333306] Random charset to be 7bit ASCII collection

- UploadServiceLogo/__test__/handler.test.ts
- UploadServiceLogo/function.json
- UploadServiceLogo/handler.ts
- UploadServiceLogo/index.ts
- utils/config.ts
This PR introduce lowercase transformation on blob name while uploading a service logo, due to wrong discovery by IO-APP that uses lowercase naming convention.
It also introduce the azure storage' sdk usage, because these kind of transformations (lowercase of the variables) are not allowed in azure bindings approach.
So changes can be resumed as follow:
* Out binding deletion (blob type) on `function.json`;
* Handler now use `blobService`, in order to write blob on `AssetsStorage` identified by `AssetsStorageConnection` config variable;
* Config module now handle `AssetsStorageConnection` that was missing;
* Tests refactoring due to implementation changes;
> [#175374436] Allow lowercase transformation on png naming while uploading a Service image Logo

- UpdateUser/handler.ts
This PR contains an improvement on `updateUser` error mapping.
> [#175440869] Improve Error mapping on UpdateUser log

- UserDataDeleteOrchestrator/__tests__/handler.test.ts
- UserDataDeleteOrchestrator/handler.ts
That was set to `ABORTED` by mistake. Please remind that this process is triggered by an incoming `ABORTED` record on the `user-data-processing` collection, so this bug used to lead to 2 `ABORTED` statuses in a row.
Anyway, that is not an issue at application level.
> [#175497987] fix final status on abort

- openapi/index.yaml
Add ServicePayload, HiddenServicePayload, VisibleServicePayload and CommonServicePayload to openapi definition.
These changes are required due to the following known issue on `pagopa/io-utils`: https://github.com/pagopa/io-utils#a-model-file-for-a-definition-is-not-generated
> [#175160851] Fix service model openapi

- azure-templates/deploy-steps.yml
- add new parameter **containerInstanceResourceGroup**
- add **checks** if exists target vnet and subnet to avoid to create new vnet or subnet
> [#175594485] Fix healthcheck gate deploy pipeline

- .devops/azure-templates/setup-project.yml
- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
Following https://github.com/pagopa/io-functions-admin/pull/120 we add:
* use a setup template 
* fix hit cache variable
* update template version
> [#175476527] Refactor pipeline / 2

- openapi/index.yaml
- package.json
- yarn.lock
Since _[io-functions-commons/definitions.yaml](https://github.com/pagopa/io-functions-commons/blob/v18.0.7/openapi/definitions.yaml)_  has changed starting from version 19, this projects wasn't able to get builded anymore.
It's very urgent to fix it by setting a well-known version instead of relying on master one.
This problem is also affecting io-functions-service since is using this api, as visible [here](https://dev.azure.com/pagopa-io/io-functions-services/_build/results?buildId=11190&view=logs&j=976c91a6-2764-5391-e3d8-1993e9979d4d&t=976c91a6-2764-5391-e3d8-1993e9979d4d)
> Fix build by setting a well-known version for io-functions-commons definitions

- .devops/deploy-pipelines.yml
Make client SDK generation template italia-utils instead of @pagopa/openapi-codegen-ts, to avoid generation errors
> Fix Client SDK Generation

- .devops/deploy-pipelines.yml
Moved to new codegen for client sdk generation
> Moved to new codegen for client sdk generation

- CreateDevelopmentProfile/index.ts
- CreateService/index.ts
- CreateSubscription/index.ts
- CreateUser/index.ts
- GetFailedUserDataProcessing/index.ts
- GetFailedUserDataProcessingList/index.ts
- GetService/index.ts
- GetServices/index.ts
- GetSubscriptionKeys/index.ts
- GetUser/index.ts
- GetUsers/index.ts
- Info/index.ts
- RegenerateSubscriptionKeys/index.ts
- UpdateService/index.ts
- UpdateUser/index.ts
- UpdateUserGroups/index.ts
- UploadOrganizationLogo/index.ts
- UploadServiceLogo/index.ts
- UserDataProcessingProcessFailedRecords/index.ts
- package.json
- yarn.lock
- Removed io-functions-express from dependencies
- Added @pagopa/express-azure-functions
- Updated @pagopa/io-functions-commons
We want to keep dependencies updated and coherent between projects.
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test
> [#IP-224] Updated dependencies and imports

- UserDataDeleteOrchestrator/__tests__/handler.test.ts
- UserDataDeleteOrchestrator/handler.ts
- UserDataDownloadOrchestrator/__tests__/handler.test.ts
- UserDataDownloadOrchestrator/handler.ts
- UserDataProcessingRecoveryOrchestrator/__tests__/handler.test.ts
- UserDataProcessingRecoveryOrchestrator/handler.ts
- Added retry to SetUserDataProcessingStatusActivity calls
- updated tests to consider retryOptions as parameter
We want to retry the operation if we fail to set a user_data_processing status.
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test
> [#IP-256] Added retry to SetUserDataProcessingStatusActivity calls

- GetUserDataProcessingActivity/__tests__/handler.test.ts
- IsFailedUserDataProcessingActivity/__tests__/handler.test.ts
- IsFailedUserDataProcessingActivity/function.json
- IsFailedUserDataProcessingActivity/handler.ts
- IsFailedUserDataProcessingActivity/index.ts
- UserDataDeleteOrchestrator/__tests__/handler.test.ts
- UserDataDeleteOrchestrator/handler.ts
- __mocks__/durable-functions.ts
- Added activity to check if a request has previously failed
- Added a spy on context mock
- Changed the logic of UserDataProcessingDeleteOrchestrator
- Added more tests
We want to run a recovery on FAILED delete requests by setting them to PENDING again and letting the orchestrator do the job. 
There are 3 points to respect:
- No grace period is waited for failed requests
- No email is sent for failed requests
- Everything must work as expected for new request
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test
- tested on io-mock for the part regarding the new called activity to verify it's being called correctly
> [#IP-154] UserDataProcessingDeleteOrchestrator can manage previous failed requests if they are resumed

- utils/random.ts
Quick fix adding `X` and `x` to the set of allowed symbols.
> Add uppercase and lowercase X to symbols

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- Upgrade azure devops templates ref to v17
- New healthcheck management
Fix healthcheck
> [#IP-417]  Fix healthcheck stage

- .devops/deploy-pipelines.yml
- package.json
- yarn.lock
Update codegen to fix client SDK generation
Client SDK generation fix
> [#ip-457] Update codegen to fix client SDK generation

- CreateService/function.json
- UpdateService/function.json
Remove orchestration client from `CreateService` and `UpdateService`
The orchestration client in `CreateService` and `UpdateService` function is unused after pagopa/io-functions-admin#181
not tested
> [#IC-356] Remove unused Orchestration Client

- ExtractUserDataActivity/__tests__/handler.test.ts
- ExtractUserDataActivity/handler.ts
- ExtractUserDataActivity/index.ts
- __mocks__/mocks.ts
- utils/__tests__/userData.test.ts
- utils/userData.ts
Added `servicesPreferences` field to `AllUserData` type
I did a mini refactor on the pipeline for the user data fetch replacing some `sequenceS` with `bind` structure where parallel tasks wasn't needed 
At the moment the servicesPreferences of a profile are not being added to the data a user downloads their data
The entire flow of adding some preferences and downloading the data was tested through the `io-mock` project
Tests passing
The delete procedure already eliminates the preferences, so testing wasn't needed in that front.
> [#IOCIT-105] added servicesPreferences to profile data download

- GetUser/__tests__/handler.test.ts
- GetUser/handler.ts
- GetUserSubscriptions/__tests__/handler.test.ts
- GetUserSubscriptions/handler.ts
- openapi/index.yaml
* remove subscriptions query
We don't need to return subscription list when getting user's info
- [*] New feature (non-breaking change which adds functionality)
> [#IOPAE-88] Remove subscriptions

- CreateSubscription/__tests__/handler.test.ts
- CreateSubscription/handler.ts
- openapi/index.yaml
- package.json
- utils/__tests__/retry.test.ts
- utils/apim.ts
- utils/retry.ts
- yarn.lock
See commit list
Azure API Management may fail to create too many subscriptions for the same account. According to Microsoft support, this is due to its internal optimistic consistency mechanism. Such failures do not depend on us or on a specific traffic pattern and are non-deterministic from our perspective; nevertheless, they are treated as generic server errors 500 and are hard to be monitored apart and react to differently.
To improve our users' experience we decided to:
* retry up to 3 times on the `subscriptions.createOrUpdate` operation when a 412 error is returned, so our users do not have to care about anything at the cost of a slightly-higher response time
* respond with 429 if retries do not solve, so that they can regulate request rate themselves (it will also be helpful for us …
> [#IOPSC-118] Respond with 'too many requests' status code when creating too much subscriptions for the same account

- utils/__tests__/apim.test.ts
- utils/apim.ts
Fix on https://github.com/pagopa/io-functions-admin/pull/202
> [#IOPSC-118] fixed utils

- SetUserSessionLockActivity/__tests__/handler.test.ts
- SetUserSessionLockActivity/handler.ts
- package.json
- utils/__tests__/sessionApiClient.test.ts
- utils/sessionApiClient.ts
- yarn.lock
1. imported io-backed package
2. removed script that generated definition from specification
3. switched to package sdk
to speed up build time
> use reference to package SDK

- UpdateService/__tests__/handler.test.ts
- UpdateService/handler.ts
- __mocks__/mocks.ts
The new `io-services-cms` has a functionality to sync back and forth the services between the new and the legacy containers:
- When a service is created/updated using the new APIs it is also written into the legacy container and marked with a field `cmsTag`
- When a service is created/updated using the old APIs a CosmosDBTrigger Azure Function will intercept it an write it into the new container but 
only if the `cmsTag` field is not present, so when a service is updated using the old APIs the "cmsTag" field needs to be removed.
- Remove `cmsTag` before updating a service
Unit Test
> [#IOPAE-431] Delete cmsTag field before updating a service
