GetSubscriptionKeys/__tests__/handler.test.ts
GetSubscriptionKeys/handler.ts
GetUsers/__tests__/handler.test.ts
GetUsers/function.json
GetUsers/handler.ts
GetUsers/index.ts
README.md
RegenerateSubscriptionKeys/__test__/handler.test.ts
RegenerateSubscriptionKeys/handler.ts
env.example
openapi/index.yaml
package.json
utils/apim.ts
utils/conversions.ts
utils/middlewares/cursorMiddleware.ts
utils/middlewares/skipMiddleware.ts
yarn.lock

This PR aims to add a new function to list the users with a subscription.

[#171405467] Add function to list users

---

CreateUser/__tests__/handler.ts
CreateUser/handler.ts
openapi/index.yaml
utils/conversions.ts

This PR aims to change the success response payload of the CreateUser function in order to contain a subset of the UserContract properties.

[#171787815] user creation response payload

---

ExtractUserDataActivity/handler.ts

[#172621882] small refactor: generate zip with user data

---

ExtractUserDataActivity/__tests__/handler.test.ts
ExtractUserDataActivity/handler.ts

Set content type `application/zip` to the zip bundle containing user data

[#173896737] User data bundle content type

---

package.json
utils/conversions.ts
yarn.lock

This PR contains a minor refactoring to `ServiceMetadata` utility mapping due to new version of io-function-commons.

[#174770172] Service metadata mapping refactoring

---

azure-templates/deploy-steps.yml

Change deployment slot from production to staging

---

azure-templates/deploy-steps.yml

fix resource group on log and delete commands

[#175594485] Fix healthcheck gate deploy pipeline 2

---

UploadOrganizationLogo/index.ts
UploadServiceLogo/index.ts

The same of #110, but we start it over due to pipeline issues

[175892280] REDO: Update max body size for logo update

---

package.json
yarn.lock

This PR upgrade _io-functions-express_ to 1.0.0

[#175892280] Upgrade io-functions-express

---

azure-pipelines.yml
azure-templates/deploy-steps.yml

Replaces health-check pipeline step with the one from azure templates.

[#175126219] Replace pipeline step with template

---

extensions.csproj
host.json

This is required in order to mitigate bug release on current version of Azure Functions runtime.

[#IP-179] Mitigation for the Azure Durable Functions extension error 

---

.devops/deploy-pipelines.yml

- azure-pipeline-templates from v14 to v15
Not tested, it should provide healthcheck success when deploying.

[#IP-254] Updated pipeline version

---

GetFailedUserDataProcessing/__tests__/handler.test.ts
GetFailedUserDataProcessing/handler.ts
GetFailedUserDataProcessing/index.ts
GetFailedUserDataProcessingList/__tests__/handler.test.ts
GetFailedUserDataProcessingList/handler.ts
GetFailedUserDataProcessingList/index.ts
SetUserDataProcessingStatus/__tests__/handler.test.ts
SetUserDataProcessingStatus/function.json
SetUserDataProcessingStatus/handler.ts
SetUserDataProcessingStatus/index.ts

- New function to set CLOSED or PENDING status to a specific user-data-processing
We want to be able to set:
- CLOSED status to close any user-data-processing request
- PENDING status to restart any user-data-processing request
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test
- some PUT requests made with postman

[#IP-259] New function to set CLOSED or PENDING status to a specific user-data-processing

---

.github/PULL_REQUEST_TEMPLATE.md
CreateDevelopmentProfile/handler.ts
DeleteUserDataActivity/__tests__/backupAndDelete.test.ts
DeleteUserDataActivity/backupAndDelete.ts
DeleteUserDataActivity/handler.ts
DeleteUserDataActivity/index.ts
__mocks__/mocks.ts
package.json
utils/extensions/models/service_preferences.ts
yarn.lock

- Upgrade `@pagopa/io-functions-commons` to version `20.5.4`
- Add PULL_REQUEST_TEMPLATE
- Add backup&delete of `service_preferences` records

[#IP-281]  Delete ServicePreferences on Profile delete

---

openapi/index.yaml
package.json
utils/conversions.ts
yarn.lock

Upgrade definitions of `io-functions-commons` for `SpecialServices`.
Upgrade `apiServiceToService` method to support `SpecialServices`.
`io-fn-admin` should handle `SpecialServices` come from `io-fn-services` and `devportal-backend`.
unit test

[#IC-46] Special service model upgrade

---

UserDataDeleteOrchestratorV2/__tests__/handler.test.ts
UserDataDeleteOrchestratorV2/handler.ts

Added retry to the session lock activity call.
We don't want the delete to fail because of a failed sessions lock.
- yarn build
- yarn test
- yarn lint

[#IOCIT-158] Added retry to session lock

---

GetUserSubscriptions/__tests__/handler.test.ts
GetUserSubscriptions/function.json
GetUserSubscriptions/handler.ts
GetUserSubscriptions/index.ts

This PR add the GetUserSubscriptions function to retrieve user data and user subscriptions.

[IOPAE-86] Add GetUserSubscriptions function

---

openapi/index.yaml

Add new Get API "Get user subscriptions"
ADD OpenApi spec
A new endpoint has been added
Tested with Swagger editor

[#IOPAE-86] GetUserSubscriptions endpoint specification

---

CreateSubscription/handler.ts

Remove retries as it increases response time above expectations

Revert #202

---

utils/fetch.ts

Fix agent for both HTTP/HTTPS support

---

.devops/code-review-pipelines.yml
.github/workflows/pr-title-linter-and-linker.yaml
Dangerfile.ts
host.json
package.json
yarn.lock

[#IOCIT-279] Use INTERNAL_STORAGE_CONNECTION_STRING

---

GetSubscription/__tests__/handler.test.ts
GetSubscription/function.json
GetSubscription/handler.ts
GetSubscription/index.ts
openapi/index.yaml
utils/__tests__/apim.test.ts
utils/apim.ts

Added new **GetSubscription** admin API
- Added new GetSubscription API
Used to retrieve a single subscription starting from a subscriptionId

[#IOPAE-141]  Add GetSubscription admin API

---

GetSubscription/function.json

Fix _GetSubscription_ **subscriptionid** path param.
- GetSubscription function.json route definition

[#IOPAE-171] Fix GetSubscription path param

---

GetSubscription/__tests__/handler.test.ts
GetSubscription/function.json
GetSubscription/handler.ts

Update GetSubscription implementation
- GetSubscription handler review
Unit Tests

[#IOPAE-171] Update GetSubscription implementation

---

GetSubscriptionCidrs/__tests__/handler.test.ts
GetSubscriptionCidrs/function.json
GetSubscriptionCidrs/handler.ts
GetSubscriptionCidrs/index.ts
openapi/index.yaml

Add new _GetSubscriptionCidrs_ admin API.
Instead of update current GetSubscription API _(we want to avoid db connections for an endpoint used in a context where cidrs are not necessary)_, we prefer to add a dedicated API for getting specific subscription cidrs.
- new _GetSubscriptionCidrs_
We need to get Subscription Cidrs on admin level.
Unit Tests

[#IOPAE-206] Add GetSubscriptionCidrs API

---

UpdateSubscriptionCidrs/__tests__/handler.test.ts
UpdateSubscriptionCidrs/handler.ts
openapi/index.yaml

Change UpdateSubscriptionCidrs response type from `CIDRsPayload` to `SubscriptionCidrs`.
- UpdateSubscriptionCidrs handler
- UpdateSubscriptionCidrs unit tests
- openapi specifications
Unit Tests

[IOPAE-223] Change UpdateSubscriptionCidrs response

---

package.json
yarn.lock

* Update `@pagopa/express-azure-functions` in order to be based on Node 18
This change is needed in order to complete the migration to Node 18

[IOCOM-165] Update @pagopa/express-azure-functions in order to be based on Node 18

---

package.json
yarn.lock

[IOCOM-167] Update express-azure-functions to fix destroy error

---

SanitizeProfileEmail/__tests__/handler.spec.ts
SanitizeProfileEmail/handler.ts
SanitizeProfileEmail/index.ts
package.json
yarn.lock

Add `io.citizen-auth.reset_email_validation` event tracking with sha(256) as `User id` (see the screenshot)
This custom event allows us to track the progress of the profile email sanitification
unit + e2e

[IOPID-1290] Track "io.citizen-auth.reset_email_validation" event

---

.sonarcloud.properties
UserDataDeleteOrchestratorV2/__tests__/handler.test.ts
UserDataDeleteOrchestratorV2/handler.ts
UserDataDeleteOrchestratorV2/index.ts
utils/config.ts

This PR depends on https://github.com/pagopa/io-infra/pull/893
- [[#IOPID-1471] add new env variable INSTANT_DELETE_ENABLED_USERS](https://github.com/pagopa/io-functions-admin/commit/d79b68aa0b157c64f70511f28bcb829c2569f5fc)
- [[#IOPID-1471] add new condition for reducing delete grace period](https://github.com/pagopa/io-functions-admin/commit/d34faea45706b6fbf4f3a9fcf295f42d32b402d5)
- [[#IOPID-1471] fix tests + add new](https://github.com/pagopa/io-functions-admin/commit/b41b515198c9c61db7030d7427fd3a85ada99af4)
- [[#IOPID-1471] boyscout rule: resolve TS compilation errors](https://github.com/pagopa/io-functions-admin/commit/488b60610841e9e3bed1a7e8c16ac5dba837bb4c)
- [[#IOPID-1471] exclude tests from SonarCloud checks](https://github.com/pagopa/io-functions-admin/pull/230/commits/252eca …

[#IOPID-1471] Allow beta tester to delete profile without waiting grace period

---

CreateSubscription/__tests__/handler.test.ts
CreateSubscription/handler.ts
GetImpersonateService/__tests__/handler.test.ts
GetSubscription/__tests__/handler.test.ts
GetSubscription/handler.ts
GetSubscriptionKeys/__tests__/handler.test.ts
GetSubscriptionKeys/handler.ts
GetUser/__tests__/handler.test.ts
GetUser/handler.ts
GetUserSubscriptions/__tests__/handler.test.ts
GetUserSubscriptions/handler.ts
GetUsers/__tests__/handler.test.ts
GetUsers/handler.ts
GetUsers/index.ts
README.md
RegenerateSubscriptionKeys/__test__/handler.test.ts
RegenerateSubscriptionKeys/handler.ts
UpdateSubscriptionCidrs/__tests__/handler.test.ts
UpdateUserGroups/__tests__/handler.ts
UpdateUserGroups/handler.ts
package.json
utils/apim.ts
utils/config.ts
utils/conversions.ts
utils/testSupport.ts
yarn.lock

Update the Arm Api Management SDK cause support for the currently used version will be retired by Microsoft on June 1st 2024.
- Updated dependency "@azure/arm-apimanagement" from `5.1.1` to `9.1.0`
- Updated dependency "@azure/graph" from `4.0.1` to `5.0.3`
- Updated dependency "@azure/ms-rest-js" from `2.6.4` to `2.7.0`
- Updated dependency "@azure/ms-rest-nodeauth" from `2.0.6` to `3.1.1`
- Added dependency "@azure/identity"
- Edited all Azf which was using those dependencies
- Updated All unit tests
- Unit Test
- Local application run comparing responses and behaviour between the local updated App and del Deployed ones

[IOPAE-1133] Upgrade arm-apimanagement sdk

---

SanitizeProfileEmail/__tests__/handler.spec.ts
SanitizeProfileEmail/handler.ts

[#IOPID-1885] SanitizeProfileEmail: check case insensitive

---

CheckXmlCryptoCVESamlResponse/__tests__/utils.test.ts
CheckXmlCryptoCVESamlResponse/function.json
CheckXmlCryptoCVESamlResponse/index.ts
CheckXmlCryptoCVESamlResponse/utils.ts
package.json
utils/config.ts
yarn.lock

CheckXmlCryptoCVESamlResponse fn

---

Info/handler.ts
SetUserSessionLockActivity/index.ts
utils/config.ts

- Remove Backend configuration
- Switch to the new session manager internal

[#IOPID-2222] Switch internal client

---

.github/workflows/deploy-pipelines-itn.yaml

[#IOPLT-1349]add action for deploy on new func admin on itn
